### ISSUE TITLE
Is caching specific instance of a module possible?

### ISSUE THREAD

**Issue by MohitBurkule** [meakbiyik/torchcache#1]
I am training a student-teacher model where both the teacher and the student are the same network architecture ( module code) , but the student is smaller . The teacher network is frozen, and I want to cache its outputs, while not caching student's outputs

Currently, I can create a dummy wrapper around the teacher and cache its outputs, but I am wondering if there is a native way in torchcache to achieve this.
Use Case

    Teacher Network: Frozen, identical to the student network.
    Student Network: Same architecture as the teacher but smaller version ( __init__ is passed different model size parameters)
    Requirement: Cache the outputs of the teacher network to avoid redundant computations.

Thank you for your assistance!

**Comment by meakbiyik** [comment]
Good idea @MohitBurkule! I implemented the feature, and added the documentation on how to achieve that. I will release it after the CI passes.

**Comment by meakbiyik** [comment]
I just released it, it should be up in an hour or so. For instructions on how to achieve selective enablement per instance, see: https://torchcache.readthedocs.io/en/latest/usage.html#selectively-enabling-torchcache-for-module-instances
